package ch.purbank.core.domain.enums;

public enum AuditAction {
    // Authentication actions
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    TOKEN_REFRESHED,
    PASSWORD_CHANGED,

    // User management
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_STATUS_CHANGED,
    EMAIL_VERIFIED,

    // Konto management
    KONTO_CREATED,
    KONTO_UPDATED,
    KONTO_CLOSED,
    KONTO_BALANCE_ADJUSTED,
    KONTO_INTEREST_RATE_CHANGED,
    KONTO_MEMBER_ADDED,
    KONTO_MEMBER_REMOVED,
    KONTO_MEMBER_ROLE_CHANGED,

    // Transaction operations
    TRANSACTION_CREATED,
    TRANSACTION_UPDATED,
    TRANSACTION_DELETED,

    // Payment operations
    PAYMENT_INITIATED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    PAYMENT_EXECUTED,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,
    PAYMENT_UPDATED,
    PAYMENT_DELETED,

    // Interest operations
    INTEREST_CALCULATED,
    INTEREST_APPLIED,
    QUARTERLY_INTEREST_SETTLEMENT,

    // Security operations
    MOBILE_DEVICE_REGISTERED,
    MOBILE_DEVICE_APPROVED,
    MOBILE_DEVICE_REJECTED,
    MOBILE_DEVICE_REMOVED,
    AUTHORISATION_REQUESTED,
    AUTHORISATION_APPROVED,
    AUTHORISATION_REJECTED,

    // Registration
    REGISTRATION_STARTED,
    REGISTRATION_COMPLETED,
    REGISTRATION_CODE_USED,

    // Admin operations
    ADMIN_ACTION_EXECUTED,
    SYSTEM_CONFIGURATION_CHANGED
}